### ISSUE TITLE
Dijkstra's Shortest Path Algorithm 

### ISSUE THREAD

**Issue by abhishektandon** [abhishektandon/hacktober-algo#1]
* Implement Dijkstra's Shortest Path Algorithm in the language of your choice.
* Add your name to the Contributors list in the README.md file.
* Add a comment under this issue once you raise the PR with the number.
* Filename Format: dijkstra-username.extension
* Issue is open for all, multiple pull requests may be merged after review.
* Plagiarism is strictly condemned
* Please follow the contribution guidelines.

> Happy Coding!

**Comment by pranav6670** [comment]
Can I work on this?

**Comment by abhishektandon** [comment]
> Can I work on this?

Yes, you can, this issue is open for all. Multiple submissions may be merged after review.

**Comment by pranav6670** [comment]
> > Can I work on this?
> 
> Yes, you can. This issue is open for all, multiple pull requests may be merged after review.

Thank You!

**Comment by Lutir** [comment]
Hi, I have added the code in C++.
Here is the link for the PR: https://github.com/abhishektandon/hacktober-algo/pull/7

**Comment by abhishektandon** [comment]
> Hi, I have added the code in C++.
> Here is the link for the PR: https://github.com/abhishektandon/hacktober-algo/pull/7

Plagiarism is strictly condemned

**Comment by OfficialNMN** [comment]
Hi,I have created a Pull request by the name of Dijkstra-OfficialNMN.py.
Pls check.

**Comment by rohanjuneja97** [comment]
Hi,I have created a Pull request by the name of dijkstra's-rohanjuneja97.py
Please check #14

**Comment by NEENA-XAVIER** [comment]
Hey!
I have created a pull request....please check!

**Comment by jaypaliwal1212** [comment]
Hi!
Kindly check my PR #24

**Comment by saksham117** [comment]
Hi there!!
I have created a pull request by the name of dijkstra's-saksham117.cpp
Please check #25
