### ISSUE TITLE
Sum of Subsets (Dynamic Programming)

### ISSUE THREAD

**Issue by abhishektandon** [abhishektandon/hacktober-algo#18]
* Implement **`Sum of Subsets`** problem using **`Dynamic Programming`** in the `C` `C++` `Java` or `Python`.
* You may use either of the Top-Down or Bottom-Up approaches to solve the problem.
* Add your name to the Contributors list in the README.md file.
* Filename Format: **`username-dp-sum-of-subsets.extension`**
* Invalid PRs will be labeled **`spam`** as per [Hacktober 2020 Guidelines](https://hacktoberfest.digitalocean.com/hacktoberfest-update) 

> [Sum of Subsets [DP]](https://www.geeksforgeeks.org/subset-sum-problem-dp-25/) 
> Find all the subarrays of an array with a sum equal to `k`

###### **Say NO to Plagiarism.**

**Comment by padmaja-22** [comment]
Can I contribute?

**Comment by abhishektandon** [comment]
> Can I contribute?

sure

**Comment by padmaja-22** [comment]
Thank you!

**Comment by abhishektandon** [comment]
> Thank you!

please note there are some changes in the issue

**Comment by padmaja-22** [comment]
It is the implementation of sum of subsets in C/C++ using DP right?

**Comment by abhishektandon** [comment]
> It is the implementation of sum of subsets in C/C++ using DP right?

yes, but also need to print all the solutions and not just check if they exist

**Comment by padmaja-22** [comment]
yeah, all the subsets whose sum is equal to given sum k

**Comment by dipan010** [comment]
can I contribute ?

**Comment by abhishektandon** [comment]
> can I contribute ?

sure but please follow the contribution guidelines.

###### Say NO to Plagiarism
