### ISSUE TITLE
Divide and Conquer::Array Sum

### ISSUE THREAD

**Issue by abhishektandon** [abhishektandon/hacktober-algo#9]
* Implement a code to output the sum of an array using divide and conquer approach in C/C++ or Python
* Add the file to "Divide and Conquer" folder.
* Add your name to the Contributors list in the README.md file.
* Add a comment under this issue with the PR number
* Filename Format: dnq-array-sum-username.extension
* Plagiarism is strictly condemned. Pull requests with plagiarised code shall be labelled "invalid".
* Please follow the contribution guidelines.
> Happy Coding

**Comment by zainbinfurqan** [comment]
i have added a file with code #11

**Comment by SaratAngajalaoffl** [comment]
my PR #12

**Comment by joshuanussbaum** [comment]
implemented with #13 !
